---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
      memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.0
  - name: macosx-10.10
    driver:
      box: macosx-10.10

suites:
  - name: firefox_test
    run_list:
      - recipe[firefox_test::default]
      - recipe[firefox_test::version]
      - recipe[firefox_test::x11]
    attributes:

  - name: firefox_custom_version_test
    run_list:
      - recipe[firefox_test::default]
    attributes: { firefox: { version: "28.0+build2-0ubuntu2" } }
    excludes:
      - ubuntu-12.04
      - centos-6.5
      - centos-7.0
      - macosx-10.10
